API:
  ports:
  - 80:3000/tcp
  restart: always
  tty: true
  image: innroad/slack_yelp
  stdin_open: true
SlackLB:
  ports:
  - 80:3000
  restart: always
  labels:
    io.rancher.scheduler.affinity:host_label: scheduling=slacklb
  tty: true
  image: rancher/load-balancer-service
  links:
  - API:API
  stdin_open: true
